# Generated by Django 4.2.23 on 2025-07-13 09:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_role_customuser_speciality_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalreport',
            name='doctor_remarks',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='medicalreport',
            name='doctor_verdict',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicalreport',
            name='reviewed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='medicalreport',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctor_reviews', to=settings.AUTH_USER_MODEL),
        ),
    ]
