# Generated by Django 4.2.23 on 2025-07-20 14:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_sentreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='SentSymptomReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=100)),
                ('patient_age', models.IntegerField()),
                ('patient_gender', models.CharField(max_length=10)),
                ('symptoms', models.TextField()),
                ('ai_analysis', models.TextField()),
                ('reviewed', models.BooleanField(default=False)),
                ('doctor_verdict', models.BooleanField(blank=True, null=True)),
                ('doctor_remarks', models.TextField(blank=True)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_symptom_reports', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='symptom_reviews', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
