# Generated by Django 4.2.23 on 2025-07-20 18:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_sentsymptomreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='VaultReviewNew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_id', models.IntegerField()),
                ('accepted', models.BooleanField(default=False)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('source', models.CharField(choices=[('symptom-based', 'Symptom Based'), ('medical-report', 'Medical Report')], max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_vault_reviews', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vault_reviews', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
